wget http://ncert.nic.in/textbook/pdf/aeen1dd.zip
wget http://ncert.nic.in/textbook/pdf/ahhn1dd.zip
wget http://ncert.nic.in/textbook/pdf/aulb1dd.zip
wget http://ncert.nic.in/textbook/pdf/auri1dd.zip
wget http://ncert.nic.in/textbook/pdf/been1dd.zip
wget http://ncert.nic.in/textbook/pdf/bemh1dd.zip
wget http://ncert.nic.in/textbook/pdf/bhhn1dd.zip
wget http://ncert.nic.in/textbook/pdf/bhmh1dd.zip
wget http://ncert.nic.in/textbook/pdf/buib1dd.zip
wget http://ncert.nic.in/textbook/pdf/buri1dd.zip
wget http://ncert.nic.in/textbook/pdf/ceap1dd.zip
wget http://ncert.nic.in/textbook/pdf/ceen1dd.zip
wget http://ncert.nic.in/textbook/pdf/cemh1dd.zip
wget http://ncert.nic.in/textbook/pdf/chap1dd.zip
wget http://ncert.nic.in/textbook/pdf/chhn1dd.zip
wget http://ncert.nic.in/textbook/pdf/chmh1dd.zip
wget http://ncert.nic.in/textbook/pdf/cuap1dd.zip
wget http://ncert.nic.in/textbook/pdf/culb1dd.zip
wget http://ncert.nic.in/textbook/pdf/curi1dd.zip
wget http://ncert.nic.in/textbook/pdf/deap1dd.zip
wget http://ncert.nic.in/textbook/pdf/deen1dd.zip
wget http://ncert.nic.in/textbook/pdf/demh1dd.zip
wget http://ncert.nic.in/textbook/pdf/dhap1dd.zip
wget http://ncert.nic.in/textbook/pdf/dhhn1dd.zip
wget http://ncert.nic.in/textbook/pdf/dhmh1dd.zip
wget http://ncert.nic.in/textbook/pdf/duap1dd.zip
wget http://ncert.nic.in/textbook/pdf/dulb1dd.zip
wget http://ncert.nic.in/textbook/pdf/duri1dd.zip
wget http://ncert.nic.in/textbook/pdf/eeap1dd.zip
wget http://ncert.nic.in/textbook/pdf/eeen1dd.zip
wget http://ncert.nic.in/textbook/pdf/eemh1dd.zip
wget http://ncert.nic.in/textbook/pdf/ehap1dd.zip
wget http://ncert.nic.in/textbook/pdf/ehhn1dd.zip
wget http://ncert.nic.in/textbook/pdf/ehmh1dd.zip
wget http://ncert.nic.in/textbook/pdf/euev1dd.zip
wget http://ncert.nic.in/textbook/pdf/eulb1dd.zip
wget http://ncert.nic.in/textbook/pdf/euma1dd.zip
wget http://ncert.nic.in/textbook/pdf/fehl1dd.zip
wget http://ncert.nic.in/textbook/pdf/fepw1dd.zip
wget http://ncert.nic.in/textbook/pdf/fesc1dd.zip
wget http://ncert.nic.in/textbook/pdf/fess1dd.zip
wget http://ncert.nic.in/textbook/pdf/fess2dd.zip
wget http://ncert.nic.in/textbook/pdf/fhdv1dd.zip
wget http://ncert.nic.in/textbook/pdf/fhsc1dd.zip
wget http://ncert.nic.in/textbook/pdf/fhss1dd.zip
wget http://ncert.nic.in/textbook/pdf/fhss2dd.zip
wget http://ncert.nic.in/textbook/pdf/fhvs1dd.zip
wget http://ncert.nic.in/textbook/pdf/fuaz1dd.zip
wget http://ncert.nic.in/textbook/pdf/fuhm1dd.zip
wget http://ncert.nic.in/textbook/pdf/fujp1dd.zip
wget http://ncert.nic.in/textbook/pdf/furi1dd.zip
wget http://ncert.nic.in/textbook/pdf/fuse1dd.zip
wget http://ncert.nic.in/textbook/pdf/fuss1dd.zip
wget http://ncert.nic.in/textbook/pdf/fuug1dd.zip
wget http://ncert.nic.in/textbook/pdf/fuzm1dd.zip
wget http://ncert.nic.in/textbook/pdf/geah1dd.zip
wget http://ncert.nic.in/textbook/pdf/geep1dd.zip
wget http://ncert.nic.in/textbook/pdf/gehc1dd.zip
wget http://ncert.nic.in/textbook/pdf/geof1dd.zip
wget http://ncert.nic.in/textbook/pdf/gess1dd.zip
wget http://ncert.nic.in/textbook/pdf/gess2dd.zip
wget http://ncert.nic.in/textbook/pdf/gess3dd.zip
wget http://ncert.nic.in/textbook/pdf/ghdv1dd.zip
wget http://ncert.nic.in/textbook/pdf/ghsc1dd.zip
wget http://ncert.nic.in/textbook/pdf/ghss1dd.zip
wget http://ncert.nic.in/textbook/pdf/ghss2dd.zip
wget http://ncert.nic.in/textbook/pdf/ghss3dd.zip
wget http://ncert.nic.in/textbook/pdf/ghvs1dd.zip
wget http://ncert.nic.in/textbook/pdf/guaz1dd.zip
wget http://ncert.nic.in/textbook/pdf/gudp1dd.zip
wget http://ncert.nic.in/textbook/pdf/gugu1dd.zip
wget http://ncert.nic.in/textbook/pdf/guha1dd.zip
wget http://ncert.nic.in/textbook/pdf/guhm1dd.zip
wget http://ncert.nic.in/textbook/pdf/guhs1dd.zip
wget http://ncert.nic.in/textbook/pdf/guhs2dd.zip
wget http://ncert.nic.in/textbook/pdf/guse1dd.zip
wget http://ncert.nic.in/textbook/pdf/guss3dd.zip
wget http://ncert.nic.in/textbook/pdf/heep1dd.zip
wget http://ncert.nic.in/textbook/pdf/hehd1dd.zip
wget http://ncert.nic.in/textbook/pdf/heih1dd.zip
wget http://ncert.nic.in/textbook/pdf/hess1dd.zip
wget http://ncert.nic.in/textbook/pdf/hess2dd.zip
wget http://ncert.nic.in/textbook/pdf/hess3dd.zip
wget http://ncert.nic.in/textbook/pdf/hess4dd.zip
wget http://ncert.nic.in/textbook/pdf/hhdv1dd.zip
wget http://ncert.nic.in/textbook/pdf/hhsb1dd.zip
wget http://ncert.nic.in/textbook/pdf/hhsc1dd.zip
wget http://ncert.nic.in/textbook/pdf/hhsk1dd.zip
wget http://ncert.nic.in/textbook/pdf/hhss1dd.zip
wget http://ncert.nic.in/textbook/pdf/hhss2dd.zip
wget http://ncert.nic.in/textbook/pdf/hhss3dd.zip
wget http://ncert.nic.in/textbook/pdf/hhss4dd.zip
wget http://ncert.nic.in/textbook/pdf/huaz1dd.zip
wget http://ncert.nic.in/textbook/pdf/hudp1dd.zip
wget http://ncert.nic.in/textbook/pdf/hugy1dd.zip
wget http://ncert.nic.in/textbook/pdf/huhi1dd.zip
wget http://ncert.nic.in/textbook/pdf/huhm1dd.zip
wget http://ncert.nic.in/textbook/pdf/hujp1dd.zip
wget http://ncert.nic.in/textbook/pdf/huss1dd.zip
wget http://ncert.nic.in/textbook/pdf/huug1dd.zip
wget http://ncert.nic.in/textbook/pdf/iebe1dd.zip
wget http://ncert.nic.in/textbook/pdf/ieeo1dd.zip
wget http://ncert.nic.in/textbook/pdf/iees1dd.zip
wget http://ncert.nic.in/textbook/pdf/iehp1dd.zip
wget http://ncert.nic.in/textbook/pdf/ielm1dd.zip
wget http://ncert.nic.in/textbook/pdf/iemo1dd.zip
wget http://ncert.nic.in/textbook/pdf/iepg1dd.zip
wget http://ncert.nic.in/textbook/pdf/iess1dd.zip
wget http://ncert.nic.in/textbook/pdf/iess2dd.zip
wget http://ncert.nic.in/textbook/pdf/iess3dd.zip
wget http://ncert.nic.in/textbook/pdf/iess4dd.zip
wget http://ncert.nic.in/textbook/pdf/ievs1dd.zip
wget http://ncert.nic.in/textbook/pdf/ievw1dd.zip
wget http://ncert.nic.in/textbook/pdf/iewe1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihkr1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihks1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihlm1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihsc1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihsh1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihsp1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihss1dd.zip
wget http://ncert.nic.in/textbook/pdf/ihss2dd.zip
wget http://ncert.nic.in/textbook/pdf/ihss3dd.zip
wget http://ncert.nic.in/textbook/pdf/ihss4dd.zip
wget http://ncert.nic.in/textbook/pdf/iict1dd.zip
wget http://ncert.nic.in/textbook/pdf/iuau1dd.zip
wget http://ncert.nic.in/textbook/pdf/iudp1dd.zip
wget http://ncert.nic.in/textbook/pdf/iugu1dd.zip
wget http://ncert.nic.in/textbook/pdf/iuhi1dd.zip
wget http://ncert.nic.in/textbook/pdf/iujp1dd.zip
wget http://ncert.nic.in/textbook/pdf/iuna1dd.zip
wget http://ncert.nic.in/textbook/pdf/iusr1dd.zip
wget http://ncert.nic.in/textbook/pdf/iuss1dd.zip
wget http://ncert.nic.in/textbook/pdf/iuss2dd.zip
wget http://ncert.nic.in/textbook/pdf/iuss4dd.zip
wget http://ncert.nic.in/textbook/pdf/jeep1dd.zip
wget http://ncert.nic.in/textbook/pdf/jeep2dd.zip
wget http://ncert.nic.in/textbook/pdf/jeff1dd.zip
wget http://ncert.nic.in/textbook/pdf/jefp1dd.zip
wget http://ncert.nic.in/textbook/pdf/jegy3dd.zip
wget http://ncert.nic.in/textbook/pdf/jehp1dd.zip
wget http://ncert.nic.in/textbook/pdf/jelm1dd.zip
wget http://ncert.nic.in/textbook/pdf/jess2dd.zip
wget http://ncert.nic.in/textbook/pdf/jess3dd.zip
wget http://ncert.nic.in/textbook/pdf/jess4dd.zip
wget http://ncert.nic.in/textbook/pdf/jewe2dd.zip
wget http://ncert.nic.in/textbook/pdf/jhep1dd.zip
wget http://ncert.nic.in/textbook/pdf/jhep2dd.zip
wget http://ncert.nic.in/textbook/pdf/jhgy3dd.zip
wget http://ncert.nic.in/textbook/pdf/jhks1dd.zip
wget http://ncert.nic.in/textbook/pdf/jhlm1dd.zip
wget http://ncert.nic.in/textbook/pdf/jhsc1dd.zip
wget http://ncert.nic.in/textbook/pdf/jhsk1dd.zip
wget http://ncert.nic.in/textbook/pdf/jhss2dd.zip
wget http://ncert.nic.in/textbook/pdf/jhss3dd.zip
wget http://ncert.nic.in/textbook/pdf/jhss4dd.zip
wget http://ncert.nic.in/textbook/pdf/jhva1dd.zip
wget http://ncert.nic.in/textbook/pdf/judp1dd.zip
wget http://ncert.nic.in/textbook/pdf/juge1dd.zip
wget http://ncert.nic.in/textbook/pdf/jujp1dd.zip
wget http://ncert.nic.in/textbook/pdf/june1dd.zip
wget http://ncert.nic.in/textbook/pdf/jusc1dd.zip
wget http://ncert.nic.in/textbook/pdf/jusr1dd.zip
wget http://ncert.nic.in/textbook/pdf/juss1dd.zip
wget http://ncert.nic.in/textbook/pdf/juss2dd.zip
wget http://ncert.nic.in/textbook/pdf/juss3dd.zip
wget http://ncert.nic.in/textbook/pdf/juss4dd.zip
wget http://ncert.nic.in/textbook/pdf/juuq1dd.zip
wget http://ncert.nic.in/textbook/pdf/kcpy1dd.zip
wget http://ncert.nic.in/textbook/pdf/keac1dd.zip
wget http://ncert.nic.in/textbook/pdf/keac2dd.zip
wget http://ncert.nic.in/textbook/pdf/kebo1dd.zip
wget http://ncert.nic.in/textbook/pdf/kebs1dd.zip
wget http://ncert.nic.in/textbook/pdf/kect1dd.zip
wget http://ncert.nic.in/textbook/pdf/kect2dd.zip
wget http://ncert.nic.in/textbook/pdf/keec1dd.zip
wget http://ncert.nic.in/textbook/pdf/keep2dd.zip
wget http://ncert.nic.in/textbook/pdf/keep3dd.zip
wget http://ncert.nic.in/textbook/pdf/keep4dd.zip
wget http://ncert.nic.in/textbook/pdf/keep5dd.zip
wget http://ncert.nic.in/textbook/pdf/kefa1dd.zip
wget http://ncert.nic.in/textbook/pdf/kegd1dd.zip
wget http://ncert.nic.in/textbook/pdf/kegy1dd.zip
wget http://ncert.nic.in/textbook/pdf/kegy3dd.zip
wget http://ncert.nic.in/textbook/pdf/kehc1dd.zip
wget http://ncert.nic.in/textbook/pdf/kehe1dd.zip
wget http://ncert.nic.in/textbook/pdf/kehe2dd.zip
wget http://ncert.nic.in/textbook/pdf/kehp1dd.zip
wget http://ncert.nic.in/textbook/pdf/kelm1dd.zip
wget http://ncert.nic.in/textbook/pdf/kelm2dd.zip
wget http://ncert.nic.in/textbook/pdf/kelm3dd.zip
wget http://ncert.nic.in/textbook/pdf/kepc1dd.zip
wget http://ncert.nic.in/textbook/pdf/keps1dd.zip
wget http://ncert.nic.in/textbook/pdf/keps2dd.zip
wget http://ncert.nic.in/textbook/pdf/kesp1dd.zip
wget http://ncert.nic.in/textbook/pdf/kest1dd.zip
wget http://ncert.nic.in/textbook/pdf/kesy1dd.zip
wget http://ncert.nic.in/textbook/pdf/kesy2dd.zip
wget http://ncert.nic.in/textbook/pdf/kevt1dd.zip
wget http://ncert.nic.in/textbook/pdf/khac1dd.zip
wget http://ncert.nic.in/textbook/pdf/khac2dd.zip
wget http://ncert.nic.in/textbook/pdf/kham1dd.zip
wget http://ncert.nic.in/textbook/pdf/khan1dd.zip
wget http://ncert.nic.in/textbook/pdf/khar1dd.zip
wget http://ncert.nic.in/textbook/pdf/khat1dd.zip
wget http://ncert.nic.in/textbook/pdf/khbo1dd.zip
wget http://ncert.nic.in/textbook/pdf/khbs1dd.zip
wget http://ncert.nic.in/textbook/pdf/khct1dd.zip
wget http://ncert.nic.in/textbook/pdf/khct2dd.zip
wget http://ncert.nic.in/textbook/pdf/khec1dd.zip
wget http://ncert.nic.in/textbook/pdf/khep2dd.zip
wget http://ncert.nic.in/textbook/pdf/khep3dd.zip
wget http://ncert.nic.in/textbook/pdf/khep4dd.zip
wget http://ncert.nic.in/textbook/pdf/khep5dd.zip
wget http://ncert.nic.in/textbook/pdf/khfa1dd.zip
wget http://ncert.nic.in/textbook/pdf/khgd1dd.zip
wget http://ncert.nic.in/textbook/pdf/khgy1dd.zip
wget http://ncert.nic.in/textbook/pdf/khgy2dd.zip
wget http://ncert.nic.in/textbook/pdf/khgy3dd.zip
wget http://ncert.nic.in/textbook/pdf/khhc1dd.zip
wget http://ncert.nic.in/textbook/pdf/khlm2dd.zip
wget http://ncert.nic.in/textbook/pdf/khps1dd.zip
wget http://ncert.nic.in/textbook/pdf/khps2dd.zip
wget http://ncert.nic.in/textbook/pdf/khpy1dd.zip
wget http://ncert.nic.in/textbook/pdf/khsk1dd.zip
wget http://ncert.nic.in/textbook/pdf/khsk2dd.zip
wget http://ncert.nic.in/textbook/pdf/khsr1dd.zip
wget http://ncert.nic.in/textbook/pdf/khst1dd.zip
wget http://ncert.nic.in/textbook/pdf/khsy1dd.zip
wget http://ncert.nic.in/textbook/pdf/khsy2dd.zip
wget http://ncert.nic.in/textbook/pdf/khvt1dd.zip
wget http://ncert.nic.in/textbook/pdf/klss1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuac1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuac2dd.zip
wget http://ncert.nic.in/textbook/pdf/kuch1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuct1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuct2dd.zip
wget http://ncert.nic.in/textbook/pdf/kucw1dd.zip
wget http://ncert.nic.in/textbook/pdf/kudh1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuec1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuga1dd.zip
wget http://ncert.nic.in/textbook/pdf/kugm1dd.zip
wget http://ncert.nic.in/textbook/pdf/kugy2dd.zip
wget http://ncert.nic.in/textbook/pdf/kuhc1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuhc2dd.zip
wget http://ncert.nic.in/textbook/pdf/kuic1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuiz1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuku1dd.zip
wget http://ncert.nic.in/textbook/pdf/kuna1dd.zip
wget http://ncert.nic.in/textbook/pdf/kups1dd.zip
wget http://ncert.nic.in/textbook/pdf/kups2dd.zip
wget http://ncert.nic.in/textbook/pdf/kupy1dd.zip
wget http://ncert.nic.in/textbook/pdf/kusc1dd.zip
wget http://ncert.nic.in/textbook/pdf/kusy1dd.zip
wget http://ncert.nic.in/textbook/pdf/kusy2dd.zip
wget http://ncert.nic.in/textbook/pdf/leac1dd.zip
wget http://ncert.nic.in/textbook/pdf/leac2dd.zip
wget http://ncert.nic.in/textbook/pdf/lebo1dd.zip
wget http://ncert.nic.in/textbook/pdf/lebs1dd.zip
wget http://ncert.nic.in/textbook/pdf/lebs2dd.zip
wget http://ncert.nic.in/textbook/pdf/leca1dd.zip
wget http://ncert.nic.in/textbook/pdf/lecs1dd.zip
wget http://ncert.nic.in/textbook/pdf/leec1dd.zip
wget http://ncert.nic.in/textbook/pdf/leec2dd.zip
wget http://ncert.nic.in/textbook/pdf/leep2dd.zip
wget http://ncert.nic.in/textbook/pdf/leep4dd.zip
wget http://ncert.nic.in/textbook/pdf/leep5dd.zip
wget http://ncert.nic.in/textbook/pdf/leep6dd.zip
wget http://ncert.nic.in/textbook/pdf/lehc1dd.zip
wget http://ncert.nic.in/textbook/pdf/lehe1dd.zip
wget http://ncert.nic.in/textbook/pdf/lehs1dd.zip
wget http://ncert.nic.in/textbook/pdf/lehs2dd.zip
wget http://ncert.nic.in/textbook/pdf/lehs3dd.zip
wget http://ncert.nic.in/textbook/pdf/leip1dd.zip
wget http://ncert.nic.in/textbook/pdf/lelm1dd.zip
wget http://ncert.nic.in/textbook/pdf/lelm2dd.zip
wget http://ncert.nic.in/textbook/pdf/lelm3dd.zip
wget http://ncert.nic.in/textbook/pdf/leph2dd.zip
wget http://ncert.nic.in/textbook/pdf/leps1dd.zip
wget http://ncert.nic.in/textbook/pdf/leps2dd.zip
wget http://ncert.nic.in/textbook/pdf/lesy1dd.zip
wget http://ncert.nic.in/textbook/pdf/lesy2dd.zip
wget http://ncert.nic.in/textbook/pdf/levt1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhac1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhac2dd.zip
wget http://ncert.nic.in/textbook/pdf/lham1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhan1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhar1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhbo1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhbs1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhbs2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhch2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhec1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhec2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhep2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhep4dd.zip
wget http://ncert.nic.in/textbook/pdf/lhep6dd.zip
wget http://ncert.nic.in/textbook/pdf/lhgy3dd.zip
wget http://ncert.nic.in/textbook/pdf/lhhc1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhhs1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhhs2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhhs3dd.zip
wget http://ncert.nic.in/textbook/pdf/lhlm1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhps1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhps2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhpy1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhsk1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhsk2dd.zip
wget http://ncert.nic.in/textbook/pdf/lhsy1dd.zip
wget http://ncert.nic.in/textbook/pdf/lhsy2dd.zip
wget http://ncert.nic.in/textbook/pdf/luab1dd.zip
wget http://ncert.nic.in/textbook/pdf/luac1dd.zip
wget http://ncert.nic.in/textbook/pdf/luac2dd.zip
wget http://ncert.nic.in/textbook/pdf/lubo1dd.zip
wget http://ncert.nic.in/textbook/pdf/lubs1dd.zip
wget http://ncert.nic.in/textbook/pdf/lubs2dd.zip
wget http://ncert.nic.in/textbook/pdf/ludh1dd.zip
wget http://ncert.nic.in/textbook/pdf/lufh1dd.zip
wget http://ncert.nic.in/textbook/pdf/luga1dd.zip
wget http://ncert.nic.in/textbook/pdf/lugy1dd.zip
wget http://ncert.nic.in/textbook/pdf/lugy3dd.zip
wget http://ncert.nic.in/textbook/pdf/luhc1dd.zip
wget http://ncert.nic.in/textbook/pdf/luis1dd.zip
wget http://ncert.nic.in/textbook/pdf/luku1dd.zip
wget http://ncert.nic.in/textbook/pdf/lume1dd.zip
wget http://ncert.nic.in/textbook/pdf/lume2dd.zip
wget http://ncert.nic.in/textbook/pdf/luna1dd.zip
wget http://ncert.nic.in/textbook/pdf/lups1dd.zip
wget http://ncert.nic.in/textbook/pdf/lupy1dd.zip
wget http://ncert.nic.in/textbook/pdf/lusy2dd.zip
wget http://ncert.nic.in/textbook/pdf/luth1dd.zip
wget http://ncert.nic.in/textbook/pdf/luth2dd.zip
wget http://ncert.nic.in/textbook/pdf/luth3dd.zip
wget http://ncert.nic.in/textbook/pdf/mehc1dd.zip
